import "./register";
export * from "./registry";
export * from "./Section";
export * from "./Hero";
export * from "./Features";
export * from "./Cta";
export * from "./Testimonials";
export * from "./Gallery";
export * from "./Pricing";
export * from "./Faq";
export * from "./Contact";
export * from "./Footer";
export * from "./About";
export * from "./Subscribe";
export * from "./Stats";
export * from "./Logos";
export * from "./Menu";
export * from "./Products";
