import { componentRegistry } from "./registry";
import { Hero } from "./Hero";
import { Features } from "./Features";
import { Cta } from "./Cta";
import { Testimonials } from "./Testimonials";
import { Gallery } from "./Gallery";
import { Pricing } from "./Pricing";
import { Faq } from "./Faq";
import { Contact } from "./Contact";
import { Footer } from "./Footer";
import { About } from "./About";
import { Subscribe } from "./Subscribe";
import { Stats } from "./Stats";
import { Logos } from "./Logos";
import { Menu } from "./Menu";
import { Products } from "./Products";
import { Navbar } from "./Navbar";

componentRegistry.register("hero", Hero);
componentRegistry.register("features", Features);
componentRegistry.register("cta", Cta);
componentRegistry.register("testimonials", Testimonials);
componentRegistry.register("gallery", Gallery);
componentRegistry.register("pricing", Pricing);
componentRegistry.register("faq", Faq);
componentRegistry.register("contact", Contact);
componentRegistry.register("footer", Footer);
componentRegistry.register("about", About);
componentRegistry.register("subscribe", Subscribe);
componentRegistry.register("stats", Stats);
componentRegistry.register("logos", Logos);
componentRegistry.register("menu", Menu);
componentRegistry.register("products", Products);
componentRegistry.register("navbar", Navbar);
