import type { LucideProps } from "lucide-react";
import {
  Zap,
  Shield,
  Code,
  Globe,
  Heart,
  Settings,
  Star,
  Check,
  X,
  Plus,
  Minus,
  Search,
  User,
  Users,
  Mail,
  Phone,
  MapPin,
  Calendar,
  Clock,
  Lock,
  Unlock,
  Eye,
  Edit,
  Trash,
  Download,
  Upload,
  Share,
  Link,
  Image,
  Video,
  File,
  Folder,
  Home,
  Building,
  Rocket,
  Target,
  TrendingUp,
  Award,
  Gift,
  Bell,
  MessageCircle,
  Send,
  Bookmark,
  Tag,
  Layers,
  Grid,
  List,
  BarChart,
  PieChart,
  Activity,
  Cpu,
  Database,
  Server,
  Cloud,
  Wifi,
  Bluetooth,
  Battery,
  Headphones,
  Camera,
  Mic,
  Volume2,
  Play,
  Pause,
  SkipForward,
  SkipBack,
  RefreshCw,
  RotateCw,
  Maximize,
  Minimize,
  Move,
  Copy,
  Clipboard,
  Save,
  Printer,
  ExternalLink,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  ChevronDown,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  AlertCircle,
  Info,
  HelpCircle,
  CheckCircle,
  XCircle,
  Lightbulb,
  Sparkles,
  Flame,
  Droplet,
  Sun,
  Moon,
  CloudRain,
  Wind,
  Compass,
  Navigation,
  Map,
  Flag,
  Briefcase,
  ShoppingCart,
  CreditCard,
  DollarSign,
  Percent,
  Package,
  Truck,
  Box,
  Archive,
} from "lucide-react";
import type { ComponentType } from "react";

type IconComponent = ComponentType<LucideProps>;

const iconMap: Record<string, IconComponent> = {
  "zap": Zap,
  "shield": Shield,
  "code": Code,
  "globe": Globe,
  "heart": Heart,
  "settings": Settings,
  "star": Star,
  "check": Check,
  "x": X,
  "plus": Plus,
  "minus": Minus,
  "search": Search,
  "user": User,
  "users": Users,
  "mail": Mail,
  "phone": Phone,
  "map-pin": MapPin,
  "calendar": Calendar,
  "clock": Clock,
  "lock": Lock,
  "unlock": Unlock,
  "eye": Eye,
  "edit": Edit,
  "trash": Trash,
  "download": Download,
  "upload": Upload,
  "share": Share,
  "link": Link,
  "image": Image,
  "video": Video,
  "file": File,
  "folder": Folder,
  "home": Home,
  "building": Building,
  "rocket": Rocket,
  "target": Target,
  "trending-up": TrendingUp,
  "award": Award,
  "gift": Gift,
  "bell": Bell,
  "message-circle": MessageCircle,
  "send": Send,
  "bookmark": Bookmark,
  "tag": Tag,
  "layers": Layers,
  "grid": Grid,
  "list": List,
  "bar-chart": BarChart,
  "pie-chart": PieChart,
  "activity": Activity,
  "cpu": Cpu,
  "database": Database,
  "server": Server,
  "cloud": Cloud,
  "wifi": Wifi,
  "bluetooth": Bluetooth,
  "battery": Battery,
  "headphones": Headphones,
  "camera": Camera,
  "mic": Mic,
  "volume": Volume2,
  "play": Play,
  "pause": Pause,
  "skip-forward": SkipForward,
  "skip-back": SkipBack,
  "refresh": RefreshCw,
  "rotate": RotateCw,
  "maximize": Maximize,
  "minimize": Minimize,
  "move": Move,
  "copy": Copy,
  "clipboard": Clipboard,
  "save": Save,
  "printer": Printer,
  "external-link": ExternalLink,
  "chevron-right": ChevronRight,
  "chevron-left": ChevronLeft,
  "chevron-up": ChevronUp,
  "chevron-down": ChevronDown,
  "arrow-right": ArrowRight,
  "arrow-left": ArrowLeft,
  "arrow-up": ArrowUp,
  "arrow-down": ArrowDown,
  "alert-circle": AlertCircle,
  "info": Info,
  "help-circle": HelpCircle,
  "check-circle": CheckCircle,
  "x-circle": XCircle,
  "lightbulb": Lightbulb,
  "sparkles": Sparkles,
  "flame": Flame,
  "droplet": Droplet,
  "sun": Sun,
  "moon": Moon,
  "cloud-rain": CloudRain,
  "wind": Wind,
  "compass": Compass,
  "navigation": Navigation,
  "map": Map,
  "flag": Flag,
  "briefcase": Briefcase,
  "shopping-cart": ShoppingCart,
  "credit-card": CreditCard,
  "dollar-sign": DollarSign,
  "percent": Percent,
  "package": Package,
  "truck": Truck,
  "box": Box,
  "archive": Archive,
};

interface FeatureIconProps {
  name: string
  size?: number
  className?: string
}

export function FeatureIcon({ name, size = 24, className }: FeatureIconProps) {
  const Icon = iconMap[name.toLowerCase()];
  if (Icon) {
    return <Icon size={size} className={className} />;
  }
  // Fallback: render as text (emoji or unknown icon name)
  return <span className={className}>{name}</span>;
}
