import { componentRegistry } from "./registry";
import { Text } from "./Text";
import { Hero } from "./Hero";
import { Features } from "./Features";
import { Cta } from "./Cta";
import { Image } from "./Image";
import { Testimonials } from "./Testimonials";
import { Gallery } from "./Gallery";
import { Pricing } from "./Pricing";
import { Faq } from "./Faq";
import { Contact } from "./Contact";
import { Footer } from "./Footer";
import { About } from "./About";
import { Subscribe } from "./Subscribe";
import { Stats } from "./Stats";
import { Logos } from "./Logos";

componentRegistry.register("text", Text);
componentRegistry.register("hero", Hero);
componentRegistry.register("features", Features);
componentRegistry.register("cta", Cta);
componentRegistry.register("image", Image);
componentRegistry.register("testimonials", Testimonials);
componentRegistry.register("gallery", Gallery);
componentRegistry.register("pricing", Pricing);
componentRegistry.register("faq", Faq);
componentRegistry.register("contact", Contact);
componentRegistry.register("footer", Footer);
componentRegistry.register("about", About);
componentRegistry.register("subscribe", Subscribe);
componentRegistry.register("stats", Stats);
componentRegistry.register("logos", Logos);
