import { componentRegistry } from "./registry";
import { TextBlock } from "./components/TextBlock";
import { HeroBlock } from "./components/HeroBlock";
import { FeaturesBlock } from "./components/FeaturesBlock";
import { CtaBlock } from "./components/CtaBlock";
import { ImageBlock } from "./components/ImageBlock";
import { TestimonialsBlock } from "./components/TestimonialsBlock";
import { GalleryBlock } from "./components/GalleryBlock";
import { PricingBlock } from "./components/PricingBlock";
import { FaqBlock } from "./components/FaqBlock";
import { ContactBlock } from "./components/ContactBlock";

componentRegistry.register("text", TextBlock);
componentRegistry.register("hero", HeroBlock);
componentRegistry.register("features", FeaturesBlock);
componentRegistry.register("cta", CtaBlock);
componentRegistry.register("image", ImageBlock);
componentRegistry.register("testimonials", TestimonialsBlock);
componentRegistry.register("gallery", GalleryBlock);
componentRegistry.register("pricing", PricingBlock);
componentRegistry.register("faq", FaqBlock);
componentRegistry.register("contact", ContactBlock);
